spring:
  mail:
    password: youpass
    username: youmail@gmail.com
    host: smtp.gmail.com
    port: 587
    from: frommail@gmail.com
    properties:
      mail:
        transport: 
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 50MB
      max-request-size: 70MB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/fenix_veiculos"
    username: fenixveiculos
    password: 12345
  flyway:
    locations: "classpath:db/migration/{vendor}"
    url: jdbc:mysql://localhost:3306/fenix_veiculos
    user: fenixveiculos
    password: 12345
server:
  base-url: http://localhost:8080
  error:
    include-stacktrace: never
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
    path: /api-docs
    groups:
      enabled: true
  group-configs:
  - group: v1
    paths-to-match:
    - /api/v1/**
#   choose packages OR paths 
#   packages-to-scan:
#   - com.example.fenixveiculos.controller.v2
jwt:
  secret: mySecret
  expiration: 604800017
file:
  local: 
    upload-dir: /home/myuser/fenix-veiculos/uploads
