spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/fenix_veiculos"
    username: fenixveiculos
    password: 12345
  flyway:
    locations: "classpath:db/migration/{vendor}"
    url: jdbc:mysql://localhost:3306/fenix_veiculos
    user: fenixveiculos
    password: 12345
server:
  error:
    include-stacktrace: never