spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/fenix_veiculos"
    username: fenixveiculos
    password: 12345
  flyway:
    locations: "classpath:db/migration/{vendor}"
    url: jdbc:mysql://localhost:3306/fenix_veiculos
    user: fenixveiculos
    password: 12345
server:
  error:
    include-stacktrace: never
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
    path: /api-docs
    groups:
      enabled: true
  group-configs:
  - group: v1
    paths-to-match:
    - /api/v1/**
#   choose packages OR paths 
#   packages-to-scan:
#   - com.example.fenixveiculos.controller.v2
